### PR TITLE
Add support for Kali Linux

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request pulls in upstream changes and adds support for Kali linux.

## 💭 Motivation and Context

We require support for Kali Linux for the Kali AMI that we are building for the COOL.

## 🧪 Testing

All pre-commit hooks and molecule tests pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by felddy — APPROVED** [review]
The triumph of this bleak, unsettling PR is that, no matter how grim it gets, it's far too involving for you to turn away. 🍅

**Comment by jsf9k** [comment]
> The triumph of this bleak, unsettling PR is that, no matter how grim it gets, it's far too involving for you to turn away.

@felddy, where are you getting these fascinating quotes?

**Comment by felddy** [comment]
> > The triumph of this bleak, unsettling PR is that, no matter how grim it gets, it's far too involving for you to turn away.
> 
> Where are you getting these fascinating quotes?

The latest are from:
https://www.rottentomatoes.com/m/rivers_edge

Previously it was from the [cover of the DVD](https://m.media-amazon.com/images/M/MV5BNzMyYzVkYjctNDliZi00Yjc0LThiODctOTc5Mzk2Njc5YzM2XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg)

**Comment by jsf9k** [comment]
> The latest are from:
> https://www.rottentomatoes.com/m/rivers_edge
> 
> Previously it was from the [cover of the DVD](https://m.media-amazon.com/images/M/MV5BNzMyYzVkYjctNDliZi00Yjc0LThiODctOTc5Mzk2Njc5YzM2XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg)

Nice! :smiley:

**Review by dav3r — APPROVED** [review]
🐪

**Pull request merged**
